dnsmasq.conf
dnsmasq.sh

This makes it easier for QA to execute the DNS sample programs without
requiring them to set up transparent proxies and/or routing/NAT.
Also add a shebang to dnsmasq.sh and change its permissions so it's
executable from the get go.
JIRA: ZEP-2040
Signed-off-by: Leandro Pereira <leandro.pereira@intel.com>

dnsmasq: Add www.zephyrproject.org to address lists

---

loop-slip-tap.sh
tunslip6.c

This makes testing compatible with programs which open a raw
socket on an interface and can't be told they need to reopen
their socket when the tap0 interface is recreated.
slipfd and inslip are reopened after a wait period when an
error occurs reading from inslip. This makes it so we don't
have to bring down the tap interface we can continue with the
new slip and the old tap in case other programs are using it.
Signed-off-by: John Andersen <john.s.andersen@intel.com>

tunslip6: reload slip without restarting tap

---

tunslip6.c

If the qemu is restarted, the tunslip6 notices it and reopens the
interface. But we should flush the neighbor cache as the MAC addresses
of the qemu zephyr instance will be changed but the IP addresses will
be the same. If we do not flush, then Linux will take several seconds
before connectivity is restored after qemu restart.

tunslip6: Flush neighbor cache when qemu restarts

---

echo-server.c

Handle the return value of tcp_receive_and_reply() properly, so the
sockets returned by accept() will be reset to -1 if connection is
closed by the peer.
Signed-off-by: Aska.Wu <aska.wu@linaro.org>

echo-server: Fix select() failed if tcp connection is closed by the peer

---

monitor_15_4.c

Some variables were not initialized properly which caused
uninitialized memory access warnings by valgrind.

monitor_15_4: Do not access uninitialized variables

---

tunslip6.c

Ethernet frame of the size 1514 may contain lots of ESC and END
data bytes that need to be escaped, thus causing the resulting
packet to grow in size. Therefore, the current SLIP buffer size
of 2000 bytes in insufficient for one frame.
Fixes #16
Signed-off-by: Ruslan Mstoi <ruslan.mstoi@linux.intel.com>

tunslip6: increase SLIP buffer size to fit escape characters

---

loop-slip-tap.sh

Use the directory of loop-slip-tap.sh to look for the tunslip6
executable. Do a loop for finding it, first look into the
current directory, then in the directory for the shell script
and last in $ZEPHYR_BASE/../net-tools as before.
Also check that tunslip6 has execute bit set.

loop-slip-tap.sh: Use directory of loop-slip-tap.sh

---

README.md
net-setup.sh
zeth-vlan.conf
zeth.conf

The net-setup.sh script can be used to create a ethernet network
interface to the host. The default name for the interface is
zeth, and default configuration file is zeth.conf.
Do ./net-setup.sh --help to see the usage.

net-setup: Add a script to setup host ethernet interface

---

README.md
loop-ppp-dev.sh
loop-pppd.sh

Two helper scripts, loop-ppp-dev.sh and loop-pppd.sh,
can be used when testing PPP.

ppp: Add instructions for using PPP in Zephyr

---

zeth.conf

DAD should not be done so that the added IPv6 address gets added
as a non-tentative address. Reason for this is that otherwise
one cannot start for example echo-server before starting qemu.
If the 2001:db8::2 address is tentative, then echo-server cannot
start unless qemu is started first. As the added IP addresses
are "fixed" in our setup, there is no need to do DAD anyway.

zeth: Do not enable DAD for added IPv6 address

---

zeth.conf

As the IPv4 address setup sets the route to the 192.0.2.0/24
subnet, there is no need to explicitly set the route to that
subnet.

zeth: No need to setup IPv4 route

---

README.docker
docker.conf
docker/Dockerfile
libcoap/examples/etsi_coaptest.sh

Improve Docker container creation and the network setup script needed to run net-tools container against Zephyr samples. See also the 'docker_samples' branch in Zephyr.

Run networking samples against Docker net-tools container

---

echo-client.c

It is useful to know how many packets were sent by echo-client,
so instead of counting the dots manually, print this information
at the end of the run.

echo-client: Print information how many packets were sent

---

docker.conf

Fix the docker and net-setup.sh script to take into account that
docker and the network is already running.

docker: Properly return values when network is already enabled

---

docker/Dockerfile
docker/mosquitto.conf

In addition to the already existing net tools, clone mosquitto
MQTT server from git, compile and install it. When running the
git clone, add any possible proxies as environment variables in
both RUN commands, e.g.:
RUN https_proxy=proxy.example.net:112 git clone https://...
When mosquitto compilation is finished, install it in the Docker
image under /usr/local/ and remove the source code and build
directory. Mosquitto also needs a user id 'mosquitto'.
As multiple FROM directives are not that helpful, count on the
gcc image to contain necessary tools and build environment.

docker: Add mosquitto MQTT server to net-tools image

---

docker/Dockerfile
docker/mosquitto-tls.conf

Add TLS configuration so that mosquitto runs on port 8883 with TLS
enabled. Install mosquitto configuration files to
/usr/local/etc/mosquitto. Install also missing directory in /var.
Re-use certificates from echo sample application with mosquitto.

docker: Add mosquitto configuration file for TLS

---

docker/Dockerfile
docker/danted.conf
docker/mosquitto.conf

Install danted SOCKS 5 proxy and configuration file to the
image. Move mosquitto port definition to the configuration
file so that any script running mosquitto from the Docker
image does not need to specify the port.

docker: Add dante SOCKS 5 proxy

---

zeth0-gptp.conf
zeth1-gptp.conf

Configuration files when having multiple gPTP ports.
Usage:
net-setup.sh -c zeth0-gptp.conf -i zeth0 start
net-setup.sh -c zeth1-gptp.conf -i zeth1 start

gptp: Add configuration for multiple gPTP ports

---

docker/Dockerfile
docker/http-server.py
docker/https-server.py

Zephyr http-client sample needs http(s) server to run
against to.

docker: Add http(s)-server.py to the container

---

docker.conf
docker/Dockerfile
docker/gptp.cfg

This allows us to run Linux gptp daemon against Zephyr gptp
sample application and to verify that the gptp stack is working
somehow.

docker: gptp: Add linuxptp daemon support to docker

---

docker/Dockerfile
docker/http-get-file-test.sh

Zephyr dumb_http_server_mt network sample needs a HTTP client
script to do queries.

docker: Add HTTP get script and curl to the container

---

docker/Dockerfile

The /net-tools/libcoap/examples/etsi_coaptest.sh needs tcpdump
to run.

docker: Add tcpdump to image for CoAP server testing

---

docker/Dockerfile
docker/http-get-file-test.sh
docker/https-server.py

Let the user to decide what listening address to bind.
Convert the script to python3.

docker: Allow user to specify the bind address

---

net-setup.sh
zeth-tunnel.conf
zeth-tunnel.conf.stop

Add a config file that can setup IP tunneling.
This is related to https://github.com/zephyrproject-rtos/zephyr/pull/32840

net-setup: Add configuration file for IP tunneling

---

zeth-tunnel.conf

The ip6ip6 tunnel was not created properly. Adjust also the
commands so that tunnels are set as expected.

tunnel: Adjusting the zeth-tunnel.conf file

---

net-capture.py

A python script that listens captured traffic from Zephyr and
prints information about received packets to stdout and optionally
save the captured data to pcap file.

net-capture: Listen captured traffic and save to pcap file

---

zeth.conf.stop

Removes the zeth network interface when executed.
Signed-off-by: Veijo Pesonen <veijo.pesonen@nordicsemi.no>

net-setup: zeth.conf.stop script

---

docker/Dockerfile
start-leshan.sh
stop-leshan.sh

Two changes in this PR:
* Latest GCC image was update to Debian Bookworm and that caused `apt install` to fail as one of the packet changed its name.
Changed the GCC to point to a named bookworm tag, so it does not automatically update to next debian release.
* Add Leshan demo server and Leshan demo bootstrap servers that we can test against.
I'm going to follow up the Zephyr repository with `docker-tests.sh` that uses this.

Add Leshan demo server and fix docker image.

---

zephyr-websocket-server.py

Otherwise python fails with following error message:
File "zephyr-websocket-server.py", line 22
server.send_message(client, message)
TabError: inconsistent use of tabs and spaces in indentation

zephyr-websocket-server.py: use tabs for indentation

---

README.docker
docker.conf
docker.conf.stop

As the docker network setup creates an interface
called net-tools0, we should equally remove that
when we stop the network.

net-setup: Add stop script for docker network

---

docker/Dockerfile
docker/connectivity-check.sh
docker/http-server.py
docker/https-server.py

This adds dnsmasq and http-server to the Docker container so that the online connectivity check feature can be tested.
The connection manager online connectivity check can be found here https://github.com/zephyrproject-rtos/zephyr/pull/63531

Online connectivity support

---

docker/dnsmasq.conf

The config file is needed by the dnsmasq process, it was not added to the repo so the docker build fails.

docker: Add missing dnsmasq.conf file to docker directory

---

websocket-console.py

This script can be used to connect to websocket console in zephyr.

websocket-console: Add a helper script for websocket console

---

README.md
loop-radvd.sh
loop-slip-tap.sh
loop-slip.sh
systemd/loop-slip-tap.service

Updates ocurrences depending on $ZEPHYR_BASE to refer to the correct placement of net-tools under tools.

treewide: place net-tools inside tools

---

net-setup.sh
zeth-multiface.conf
zeth-multiface.conf.stop

This is mainly useful for testing Ethernet bridging when using native-sim board.

net-setup: Add config for setting up multiple network interfaces

---

docker.conf.stop

If some docker instance is still using net-tools0 network, our docker.conf.stop was failing to remove the network, and therefore next time the startup was not working either.
kill all docker instances that still use the net-tools0 when we stop. This allows network to to be removed.

net-setup: Kill dockers using our network when stopping
